name = "Chemostat"
uuid = "c5987326-81b3-11ea-28dd-b531745de20f"
authors = ["josePereiro"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
